import {
  SquareDashed,
  DoorOpen,
  Bath,
  TreeDeciduous,
  Sofa,
  Wifi,
  Bed,
  Box,
  Building2,
  Flame,
  AirVent,
  WavesLadder,
  Flower2,
  SquareParking,
  WashingMachine,
  Fence,
  PanelTopClose,
  BusFront,
  Hospital,
  School,
  ShoppingBasket,
  Mailbox,
  Plane,
  Trees,
  Landmark,
  BookOpen,
  Dumbbell,
  Utensils,
  ShoppingBag,
} from "lucide-react";

export const FacilityIconMap: Record<string, React.ComponentType> = {
  area: SquareDashed,
  room: DoorOpen,
  bedroom: Bed,
  bathroom: Bath,
  outdoor: TreeDeciduous,
  furnished: Sofa,
  floor: Building2,
  parking: SquareParking,
  balcony: Fence,
  garden: Flower2,
  pool: WavesLadder,
  elevator: PanelTopClose,
  heating: Flame,
  aircon: AirVent,
  internet: Wifi,
  laundry: WashingMachine,
  storage: Box,
};

export const SurroundingPlaceIconMap: Record<string, React.ComponentType> = {
    pharmacy: Hospital,
    supermarket: ShoppingBasket,
    school: School,
    publicTransport: BusFront,
    hospital: Hospital,
    restaurant: Utensils,
    gym: Dumbbell,
    park: Trees,
    bank: Landmark,
    postOffice: Mailbox,
    airport: Plane,
    parking: SquareParking,
    university: School,
    library: BookOpen,
    mall: ShoppingBag,
};
