import {
  DoorOpen,
  Bath,
  Wifi,
  Flame,
  SquareParking,
  WashingMachine,
  Hospital,
  School,
  ShoppingBasket,
  Plane,
  BookOpen,
  Dumbbell,
  Utensils,
  ShoppingBag,
  BedDouble,
  Ruler,
  TreePalm,
  Columns3,
  Flower,
  Waves,
  Sofa,
  Layers,
  UnfoldVertical,
  ThermometerSnowflake,
  Archive,
  Pill,
  TrainFront,
  TreePine,
  Banknote,
  Mail,
  CircleParking,
  University,
} from "lucide-react";

export const FacilityIconMap: Record<string, React.ComponentType> = {
  area: Ruler,
  room: DoorOpen,
  bedroom: BedDouble,
  bathroom: Bath,
  outdoor: TreePalm,
  furnished: Sofa,
  floor: Layers,
  parking: SquareParking,
  balcony: Columns3,
  garden: Flower,
  pool: Waves,
  elevator: UnfoldVertical,
  heating: Flame,
  aircon: ThermometerSnowflake,
  internet: Wifi,
  laundry: WashingMachine,
  storage: Archive,
};

export const SurroundingPlaceIconMap: Record<string, React.ComponentType> = {
  pharmacy: Pill,
  supermarket: ShoppingBasket,
  school: School,
  publicTransport: TrainFront,
  hospital: Hospital,
  restaurant: Utensils,
  gym: Dumbbell,
  park: TreePine,
  bank: Banknote,
  postOffice: Mail,
  airport: Plane,
  parking: CircleParking,
  university: University,
  library: BookOpen,
  mall: ShoppingBag,
};
