import {
  DoorOpen,
  Bath,
  Wifi,
  Box,
  Flame,
  AirVent,
  WavesLadder,
  Flower2,
  SquareParking,
  WashingMachine,
  PanelTopClose,
  Hospital,
  School,
  ShoppingBasket,
  Mailbox,
  Plane,
  Trees,
  Landmark,
  BookOpen,
  Dumbbell,
  Utensils,
  ShoppingBag,
  TramFront,
  Scaling,
  BedDouble,
  Shrub,
  Armchair,
  Building,
} from "lucide-react";

export const FacilityIconMap: Record<string, React.ComponentType> = {
  area: Scaling,
  room: DoorOpen,
  bedroom: BedDouble,
  bathroom: Bath,
  outdoor: Shrub,
  furnished: Armchair,
  floor: Building,
  parking: SquareParking,
  balcony: Building,
  garden: Flower2,
  pool: WavesLadder,
  elevator: PanelTopClose,
  heating: Flame,
  aircon: AirVent,
  internet: Wifi,
  laundry: WashingMachine,
  storage: Box,
};

export const SurroundingPlaceIconMap: Record<string, React.ComponentType> = {
  pharmacy: Hospital,
  supermarket: ShoppingBasket,
  school: School,
  publicTransport: TramFront,
  hospital: Hospital,
  restaurant: Utensils,
  gym: Dumbbell,
  park: Trees,
  bank: Landmark,
  postOffice: Mailbox,
  airport: Plane,
  parking: SquareParking,
  university: School,
  library: BookOpen,
  mall: ShoppingBag,
};
